### ISSUE TITLE
Batch rpc calls

### ISSUE THREAD

**Issue by Eduard-Voiculescu** [streamingfast/substreams-ethereum#11]
**Do you want to request a *feature* or report a *bug*?**
Feature request

**What is the current behavior?**
Separate rpc calls

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
N/A

**What is the expected behavior?**
Instead of doing 
```
let fee0 = abi::pool::functions::FeeGrowthGlobal0X128
fee0.call(...)
let fee1 = abi::pool::functions::FeeGrowthGlobal1X128
fee1.call(...)
```
We could provide a helper to do both calls at the same time instead of doing 2 calls separately.

**Comment by maoueh** [comment]
Now possible with `RpcBatch` object
