### ISSUE TITLE
Abigen: Event::decode panics

### ISSUE THREAD

**Issue by gusinacio** [streamingfast/substreams-ethereum#21]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
The decode function generated panics if there aren't enough arguments for `log.topics` while decoding.

```
panic in the wasm: \"index out of bounds: the len is 2 but the index is 2\" at src/abi/erc20.rs:1219:29
```

```rust
...
 Ok(Self {
                    from: ethabi::decode(
                            &[ethabi::ParamType::Address],
                            log.topics[1usize].as_ref(),
                        )
                        .map_err(|e| {
                            format!(
                                "unable to decode param 'from' from topic of type 'address': {:?}",
                                e
                            )
                        })?
                        .pop()
                        .expect(INTERNAL_ERR)
                        .into_address()
                        .expect(INTERNAL_ERR)
                        .as_bytes()
                        .to_vec(),
                    to: ethabi::decode(
                            &[ethabi::ParamType::Address],
                            log.topics[2usize].as_ref(), // <- line 1219
                        )
                        .map_err(|e| {
                            format!(
                                "unable to decode param 'to' from topic of type 'address': {:?}",
                                e
                            )
                        })?
                        .pop()
                        .expect(INTERNAL_ERR)
                        .into_address()
                        .expect(INTERNAL_ERR)
                        .as_bytes()
                        .to_vec(),
...
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I'm currently doing the following:

```rust
let transfers = block
        .logs()
        .flat_map(|view| {
            match abi::erc20::events::Transfer::decode(view.log) {
               Ok(transfer) => {
                    // logic
                    Some(struct)
                },
                Err(_) => None
            }
        })
        .collect();
```
I'm trying to match every possible event, and right now I need two checks: `match_log` and then `decode`

**What is the expected behavior?**
It should return an error in the `Result` type instead of panicking.

**Comment by maoueh** [comment]
I agree, it should indeed be checked. Note that the expected behavior is to first check if the log you receive actually match the event. The `match_log` on the defined event does check that in advance.

You have the helper `events` that does match and decode automatically (See [substreams-template example](https://github.com/streamingfast/substreams-template/blob/develop/src/lib.rs#L18-L31))

For more control, you have the [match_and_decode](https://github.com/streamingfast/substreams-ethereum/blob/develop/core/src/event.rs#LL12C8-L12C24) version:

```
    blk.receipts().for_each(|receipt| {
        receipt.receipt.logs.iter().for_each(|log| {
            if let Some(_) = opensea::OrderFulfilled::match_and_decode(log) {
                substreams::log::info!("Found OpenSea order fullfilled");
            }
        })
    });
 ```

**Comment by maoueh** [comment]
Using the matcher will increase your performance if you try every logs in every blocks since it will only decode those for which the `Log` matches the event definition.

**Comment by gusinacio** [comment]
That's exactly what I was looking for: a function that match and decode without error. Thanks!
