### ISSUE TITLE
Rework crate structure

### ISSUE THREAD

**Issue by leoyvens** [streamingfast/substreams-ethereum#3]
Right now there are three crates, the main `substreams-ethereum`, `substreams-ethereum-abigen` and `substreams-ethereum-derive`.  `substreams-ethereum` depends on the other two, for re-exporting them and serving as a single entry point. However it also contains core types which other crates may want to depend on, but can't because it creates a circular dependency.

My suggestion would be to switch to a diamond structure, keeping `substreams-ethereum` as the single entrypoint which depends on all others, but move all the core types to a `substreams-ethereum-core` which depends on no other crates in the workspace, so all crates can depend on `substreams-ethereum-core` and interoperate through its types.

**Comment by leoyvens** [comment]
I'm working on this.

**Comment by jubeless** [comment]
@leoyvens makes sense. Out of curiosity I see you moved the full content of `core/src/lib.rs` into `substreams-ethereum/src/lib.rs`. I understand that `substreams-core` should not depend on any other package, as such, the `substreams-ethereum/src/lib.rs` should re-export everything pertaining to abi generation etc. 
I see you also moved `NULL_ADDRESS` as well. I would have assumed that is can stay in the core. I'm more asking here for a though experiment.

**Comment by leoyvens** [comment]
@jubeless That does make sense, I've addressed that in the PR.
